# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 爱奇艺会员签到

on:
    workflow_dispatch:
    schedule:
        - cron: "5 16 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_joy

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【爱奇艺会员签到】"
              run: |
                  node onlyOneExecute.js
              env:
                  iQIYI_COOKIE: ${{ secrets.iQIYI_COOKIE }}
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  SYNCURL: https://github.com/BlueskyClouds/My-Actions/function/raw/master/iqiyi.js
