name: qqyd

on:
  workflow_dispatch:
  schedule:
     - cron: '5 0 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
         npm install
      - name: '运行 【qqyd】'
        run: |
          node qqyd.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          URL: ${{ secrets.URL }}
          READERHEAD: ${{ secrets.READERHEAD }}
          TIMEURL: ${{ secrets.TIMEURL }}
          TIMEHEAD: ${{ secrets.TIMEHEAD }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
    
